repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # General file-formatting
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      # Python-related
      - id: debug-statements
      - id: name-tests-test
        args: ["--django"]  # Required to match on test*.py
      # Git-related
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.7
    hooks:
      - id: ruff-check
        args: ['--fix', '--unsafe-fixes']
      - id: ruff-format
