[tool.poetry]
name = "warlock"
version = "1.3.1"
description = "Python object model built on JSON schema and JSON patch."
readme = "README.md"
authors = ["Brian Waldon <bcwaldon@gmail.com>"]
maintainers = ["Jan Willhaus <mail@janwillhaus.de>"]
homepage = "http://github.com/bcwaldon/warlock"
repository = "http://github.com/bcwaldon/warlock"
license = "Apache-2.0"
keywords=["JSON schema", "JSON patch", "model validation"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 2.7",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.4",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
    { include = "warlock" },
]
include = [
  "README.md",
  "LICENSE"
]

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"
jsonschema = ">=0.7,<4"
jsonpatch = ">=0.10,<2"
six = "*"

[tool.poetry.dev-dependencies]
pytest = "^4.0"
pytest-cov = "^2.7"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | \.venv
  | venv
  | __pycache__
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
